node:
  wallet:
    path: <path/to/wallet>
    address: <address-in-wallet>
    password: <password>
  addresses:
    - <announced.address:port>
  attributes:
    - UN-LOCODE:<XX YYY>
    - Price:100000
    - User-Agent:NeoFS\/0.27

grpc:
  - endpoint: <listen.local.address:port>
    tls:
      enabled: false

storage:
  shards:
    - metabase:
        path: /storage/path/metabase
        perm: 0600
      blobstor:
        - path: /storage/path/peapod.db
          type: peapod
          perm: 0600
        - path: /storage/path/fstree
          type: fstree
          perm: 0600
          depth: 4
      writecache:
        enabled: false
      gc:
        remover_batch_size: 100
        remover_sleep_interval: 1m

logger:
  level: info

prometheus:
  enabled: true
  address: localhost:9090
  shutdown_timeout: 15s

object:
  put:
    pool_size_remote: 100

fschain:
  endpoints:
    - wss://rpc1.morph.fs.neo.org:40341/ws
    - wss://rpc2.morph.fs.neo.org:40341/ws
    - wss://rpc3.morph.fs.neo.org:40341/ws
    - wss://rpc4.morph.fs.neo.org:40341/ws
    - wss://rpc5.morph.fs.neo.org:40341/ws
    - wss://rpc6.morph.fs.neo.org:40341/ws
    - wss://rpc7.morph.fs.neo.org:40341/ws
  dial_timeout: 1m
