logger:
  level: info

fschain:
  endpoints:
    - wss://rpc01.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc02.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc03.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc04.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc05.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc06.morph.testnet.fs.neo.org:51331/ws
    - wss://rpc07.morph.testnet.fs.neo.org:51331/ws
  dial_timeout: 1m

node:
  attributes:
    - Deployed:SelfHosted
    - User-Agent:NeoFS\/0.27

prometheus:
  enabled: true
  address: localhost:9090
  shutdown_timeout: 15s

storage:
  shards:
    - metabase:
        path: /storage/metabase
        perm: 0777
      blobstor:
        - path: /storage/path/peapod.db
          type: peapod
          perm: 0600
        - path: /storage/path/fstree
          type: fstree
          perm: 0600
          depth: 4
      writecache:
        enabled: false
      gc:
        remover_batch_size: 100
        remover_sleep_interval: 1m
